### ISSUE TITLE
Incompatibility with guzzle 5

### ISSUE THREAD

**Issue by greg0ire** [Behat/WebApiExtension#22]
Due to the requirements, one cannot use guzzle 5 and the web api extension on the same project. Solution  : suggest instead of require guzzle, then detect the guzzle version in use ?

**Comment by stof** [comment]
No, it should not be changed to suggest, as it is a hard requirement. But we could change the constraint to allow both 4 and 5

**Comment by greg0ire** [comment]
That's right. I'm going to run the tests with 5, to see if the extension uses a part of the api that would have changed.

**Comment by jg-development** [comment]
What is the status of this ticket? The actual guzzle requirement conflicts with some of my projects.
This merge could help.

**Comment by greg0ire** [comment]
I discussed with @stof, and I think it will get merged, but not right now. If you are stuck, use my fork in an inline alias.

**Comment by davejenniex** [comment]
This is also conflicting with dependencies in my project also. Thanks for all the help.

**Comment by eddiejaoude** [comment]
Any movement on this or are we all using the forked version?
