### ISSUE TITLE
Guzzle version 6

### ISSUE THREAD

**Issue by nspyke** [Behat/WebApiExtension#28]
@stof 
I've upgraded my fork of this project to Guzzle version 6.
Would you be interested in merging this if I made a PR to this project?

https://github.com/nspyke/WebApiExtension/tree/1.1.1

**Comment by ArthurGuy** [comment]
+1

**Comment by koorb** [comment]
+1

**Comment by cam5** [comment]
Awe, I wish I looked here before I updated it, too, @nspyke ! +1
